//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by lameFE.rc
//
#define MANIFEST_RESOURCE_ID            2
#define IDD_ABOUTBOX                    100
#define IDD_ALBUMINFOCTRL               103
#define IDD_ENCODER_PAGE                107
#define IDD_SETTINGS_MP3                107
#define IDD_FILENAMES                   108
#define IDR_MAINFRAME                   128
#define IDD_PRESETBAR                   128
#define IDR_LAMEFETYPE                  129
#define IDR_MAIN_MENU                   129
#define IDS_THREADWARNING               129
#define IDD_FREEDB_QUERY                130
#define IDS_APPALREADYRUNNING           130
#define IDI_NEXT                        131
#define IDS_DECODER                     131
#define IDI_STOP                        132
#define IDS_ENCODER                     132
#define IDI_EJECT                       133
#define IDS_ALBUMINFO                   133
#define IDI_PREV                        134
#define IDD_PRESET                      134
#define IDS_BATCHMODE                   134
#define IDI_PLAY                        135
#define IDS_FILENAMES                   135
#define IDI_PAUSE                       136
#define IDS_LOOKNFEEL                   136
#define IDB_SPLASH                      137
#define IDS_NONESELECTED                137
#define IDS_PRESET_BLANKNAME            138
#define IDB_FREEDB                      139
#define IDD_SETTINGS                    139
#define IDD_SETTINGS_FILENAMES          139
#define IDD_ID3EDIT                     140
#define IDD_STATUS_DIALOG               142
#define IDR_CD_PLAYER                   144
#define IDD_TRACKLIST                   146
#define IDI_CONFIG_OUT                  151
#define IDI_CONFIG_IN                   152
#define IDB_IMAGES                      153
#define IDD_PATH_AND_FILENAMES          156
#define IDD_LOGGING_PAGE                158
#define IDB_LIST_BK                     159
#define IDB_TOOLBAR_256                 160
#define IDB_TOOLBAR_256_DEACT           161
#define IDB_LOG_IMAGES                  162
#define IDR_FINISHED                    163
#define IDB_BITMAP1                     164
#define IDB_TOOLBAR_HI_DEACT            164
#define IDD_LAMEFE_PAGE                 165
#define IDB_BITMAP2                     165
#define IDB_TOOLBAR_HI                  165
#define IDD_CDRIP_PAGE                  166
#define IDD_SETTINGS_CDRIPPER           166
#define IDD_CDDB_SETUP                  168
#define IDI_ICON1                       168
#define IDD_SETTINGS_FREEDB             168
#define IDR_SYSTRAY_MENU                171
#define IDD_CDDB_QUERY                  172
#define IDR_INT_PLAYER                  172
#define IDD_SETTINGSDIALOG              174
#define IDB_SETTINGS_IMAGES             175
#define IDD_SETTINGS_LAMEFE             176
#define IDD_CHECKNEWVERSION             177
#define IDD_SETTINGS_LOOKNFEEL          178
#define IDD_SETTINGS_BATCHMODE          180
#define IDD_SETTINGS_PLUGINCODEC        181
#define IDI_ENCODER                     182
#define IDI_DECODER                     183
#define IDR_MAINFRAMESMALL              184
#define IDD_PLUGINPAGE                  185
#define IDB_MENUITEMS                   185
#define IDD_SETTINGS_DECODER            188
#define IDR_PRESETBAR_2                 189
#define SPLASH                          190
#define IDD_SAVEPRESET                  191
#define IDD_SETUPWIZARD                 192
#define IDR_LIST_MENU                   195
#define IDD_FREEDB_STATUS               197
#define IDB_FREEDBLOGO                  198
#define IDC_INPUT_DEVICE                1001
#define IDC_PRESET                      1001
#define IDC_OUTPUT_DEVICE               1002
#define IDC_PROTOCOLL                   1003
#define IDC_START                       1005
#define IDC_LIST                        1005
#define IDC_ENCODE                      1006
#define IDC_STATIC_1                    1011
#define IDC_STATIC_2                    1012
#define IDC_ENCODING                    1015
#define IDC_SAMPLES                     1016
#define IDC_BITRATE                     1017
#define IDC_CONFIGURE_OUT               1017
#define IDC_ABOUT_OUT                   1018
#define IDC_ORIG                        1020
#define IDC_COPY                        1021
#define IDC_CONFIG_OUT                  1021
#define IDC_SAVE                        1022
#define IDC_CONFIG_IN                   1023
#define IDC_FILENAME_VIS                1024
#define IDC_DELETE                      1025
#define IDC_ALBUM_MODE_FILENAME         1025
#define IDC_PROGRESS_FILE               1026
#define IDC_PLAYLIST_FILENAME           1026
#define IDC_PROGRESS_LIST               1027
#define IDC_PLAYLIST_VIS                1027
#define IDC_ALBUM_MODE_VIS              1028
#define IDC_STATUS                      1029
#define IDC_START_SESSION               1031
#define IDC_LOG_ENTRY                   1032
#define IDC_END_SESSION                 1033
#define IDC_LOG                         1034
#define IDC_REPORT_STYLE                1035
#define IDC_REAL_TIME_LOG               1037
#define IDC_SAVE_LOG                    1038
#define IDC_PRINT                       1039
#define IDC_FOCUS                       1040
#define IDC_PLAY_SOUND                  1041
#define IDC_BEEP                        1042
#define IDC_PLAY                        1043
#define IDC_SAVE_WINDOW_STATE           1043
#define IDC_M3U                         1044
#define IDC_DLG                         1045
#define IDC_USE_HIGH_COLOR_ICONS        1045
#define IDC_PATHCHK                     1046
#define IDC_CONVERTTO16BIT              1046
#define IDC_ID3V1                       1047
#define IDC_PRINTMSG                    1048
#define IDC_PLAYER                      1049
#define IDC_STATUS_STRING               1049
#define IDC_STRPLAYER                   1050
#define IDC_PLAYER2                     1050
#define IDC_SHOW_SPLASH                 1050
#define IDC_LAMEVERSION                 1051
#define IDC_SONGTITLE                   1052
#define IDC_FILES                       1053
#define IDC_SONGINTERPRET               1054
#define IDC_SONG                        1055
#define IDC_ALBUMNAME                   1055
#define IDC_ARTIST                      1056
#define IDC_ALBUM                       1057
#define IDC_TRACKNUMBER                 1057
#define IDC_COMMENT                     1058
#define IDC_YEAR                        1060
#define IDC_TRACK                       1061
#define IDC_FILEN                       1062
#define IDC_RENAME                      1064
#define IDC_GENRE                       1067
#define IDC_SAVE_PATH                   1068
#define IDC_LIST_STATUS_BAR             1071
#define IDC_LIST_STATUS_BAR2            1072
#define IDC_ALBUMINFO_CTRL              1072
#define IDC_EST_SIZE                    1073
#define IDC_CHECK2                      1073
#define IDC_ALBUMEDIT                   1073
#define IDC_BATCH_BEEP                  1073
#define IDC_IN_SIZE                     1074
#define IDC_FILE_STATUS_BAR             1075
#define IDC_FILE_X_OF_Y                 1076
#define IDC_ERRORS                      1077
#define IDC_OUTPUTPATH                  1077
#define IDC_LIST_MSG                    1079
#define IDC_FILE_MSG                    1080
#define IDC_IN                          1081
#define IDC_OUT                         1082
#define IDC_ID3_TAG                     1083
#define IDC_PRESETS                     1084
#define IDC_COMBO2                      1086
#define IDC_THREADPRIORITY              1087
#define IDC_HIDEMWND_ENC                1088
#define IDC_SONG_A                      1089
#define IDC_BATCH_FREEDB                1089
#define IDC_ARTIST_A                    1090
#define IDC_BATCHTIMEOUT                1090
#define IDC_ALBUM_A                     1091
#define IDC_BATCH_TIMEOUTEDIT           1091
#define IDC_COMMENT_A                   1092
#define IDC_BATCHALLDRIVES              1092
#define IDC_GENRE_A                     1093
#define IDC_YEAR_A                      1094
#define IDC_NUMBUFFERS                  1094
#define IDC_CHECK3                      1095
#define IDC_CHECKFORNEWCD               1095
#define IDC_SHOW_TAGEDITOR_ONFILE       1095
#define IDC_TRACK_A                     1096
#define IDC_APPENDDISCID                1096
#define IDC_AM_ARTIST                   1097
#define IDC_MODULES                     1097
#define IDC_AM_ALBUM                    1098
#define IDC_AM_GENRE                    1099
#define IDC_AM_COMMENT                  1100
#define IDC_YOUR_VERSION                1100
#define IDC_AM_YEAR                     1101
#define IDC_NEWESTVERSION               1101
#define IDC_MESSAGE_VERSION             1102
#define IDC_FILE_NAME                   1103
#define IDC_DOWNLOAD                    1103
#define IDC_PLACEHOLDER_STATIC          1104
#define IDC_EXTENSIONS                  1106
#define IDC_ABOUTSTRING                 1107
#define IDC_ABOUT                       1108
#define IDC_ID3TAG                      1109
#define IDC_CONFIGURATION               1109
#define IDC_ALBUM_MODE                  1110
#define IDC_PLUGINNAME                  1110
#define IDC_CHANGELOG                   1112
#define IDC_APPLY                       1113
#define IDC_PRESETMP3DLG                1114
#define IDC_SAVEPRESET                  1115
#define IDC_SELECTPRESET                1116
#define IDC_REFRESH                     1117
#define IDC_PRESETDESCRIPTION           1117
#define IDC_PRESETPATH                  1119
#define IDC_DEFAULT_FILE                1120
#define IDC_PRESET_PATH_DISPLAY         1122
#define IDC_WINAMP_PATH                 1123
#define IDC_PATH_WINAMP                 1124
#define IDC_OUTSAMPLERATE               1125
#define IDC_REMEMBERLASTENCODER         1126
#define IDC_EJECT_CD                    1128
#define IDC_PRESETNAME                  1128
#define IDC_PRESETCOMMENT               1129
#define IDC_ENCODER_VERSION             1130
#define IDC_REMEMBER_LAST               1130
#define IDC_BITSPERSAMPLE               1132
#define IDC_CHANNELS                    1133
#define IDC_BITSPERSAMPLE_MAX           1134
#define IDC_COPYRIGHT                   1135
#define IDC_ORIGINAL                    1136
#define IDC_CHECKSUM                    1137
#define IDC_PRIVATE                     1138
#define IDC_ID3_2                       1139
#define IDC_OUTPUT                      1142
#define IDC_PLAYER_PATH                 1144
#define IDC_OUTPUT_PATH                 1145
#define IDC_FINISH_DLG                  1146
#define IDC_PLAY_FILES                  1148
#define IDC_SHUTDOWN                    1151
#define IDC_EXIT_FINISHED               1153
#define IDC_CD_DRIVE                    1154
#define IDC_CDROM_TYPE                  1155
#define IDC_RIPPING_METHOD              1156
#define IDC_EJECT                       1157
#define IDC_LOCK                        1158
#define IDC_SWAP                        1159
#define IDC_REMOTE_SERVER               1161
#define IDC_LOCATION                    1162
#define IDC_ADDRESS                     1163
#define IDC_PATH                        1164
#define IDC_REMOTE_PORT                 1166
#define IDC_EMAIL                       1167
#define IDC_TIMEOUT                     1168
#define IDC_PROXY                       1169
#define IDC_USE_PROXY                   1170
#define IDC_PROXY_PORT                  1171
#define IDC_USERNAME                    1172
#define IDC_PASSWORD                    1173
#define IDC_Version                     1174
#define IDC_CD_SPEED                    1175
#define IDC_CD_SPIN_UP                  1176
#define IDC_NATIVE                      1177
#define IDC_AUTHENTICATION              1183
#define IDC_UPDATE                      1184
#define IDC_CDDB                        1185
#define IDC_SELECT_ALL                  1189
#define IDC_EST_TIME                    1190
#define IDC_ELA_TIME                    1191
#define IDC_REM_TIME                    1192
#define IDC_MPEG                        1193
#define IDC_FORMAT                      1194
#define IDC_SUBDIR                      1195
#define IDC_SILENT                      1196
#define IDC_LIST_TITLE                  1197
#define IDC_PLUGINS                     1198
#define IDC_PLUGINPATH                  1200
#define IDC_INSTALLED_PLUGINS           1202
#define IDC_CONFIGURE                   1203
#define IDC_INSTALL                     1204
#define IDC_UNINSTALL                   1205
#define IDC_DISPLAY_STATIC              1206
#define IDC_JITTERSTATUS                1209
#define IDC_DEFAULTPLAYER               1210
#define IDC_CHANGE_PLAYER               1212
#define IDC_PATH2PLAYER                 1213
#define IDC_DEFAULT_CD                  1214
#define IDC_PLUGIN_DETAILS              1215
#define IDC_ABOUT_PLUGIN                1216
#define IDC_QUALITY                     1217
#define IDC_VBR_METHOD                  1218
#define IDC_ABR                         1219
#define IDC_COMBO3                      1221
#define IDC_VBR_QUALITY                 1221
#define IDC_LIST1                       1223
#define IDC_OUT_PLUGINS                 1223
#define IDC_FILES_TRACKS                1223
#define IDC_CPLAYERINI_ALWAYS_READ      1226
#define IDC_CPLAYERINI_ALWAYS_WRITE     1227
#define IDC_CHECK1                      1228
#define IDC_CDTEXT_ALWAYSREAD           1228
#define IDC_PLAYINGTIME                 1228
#define IDC_CUE                         1228
#define IDC_USE_LAMEFE                  1229
#define IDC_USE_WINAMP                  1230
#define IDC_STATUS_MSG                  1231
#define IDC_ENQUEUE_FILES               1232
#define ID_REMOVE_FILE                  32771
#define ID_HELP_HELPINDEX               32772
#define ID_HELP_LICENSE                 32773
#define ID_ID3TAGS_READFREEDBSERVER     32774
#define ID_ID3TAGS_READCDTEXT           32775
#define ID_ID3TAGS_READCDPLAYERINI      32776
#define ID_ID3TAGS_SAVETOCDPLAYERINI    32777
#define ID_ID3TAGS_ID3TAGEDITOR         32778
#define ID_SETTINGS_CDREADER            32779
#define ID_SETTINGS_PLUGINS             32780
#define ID_SETTINGS_PREFERENCES         32781
#define ID_SETTINGS_LAMEENCODER         32782
#define ID_SETTINGS_ID3TAGSFILENAMES    32783
#define ID_FILE_REMOVE                  32784
#define ID_SETTINGS_FREEDBSETUP         32791
#define ID_FILE_STARTENCODING           32792
#define ID_START_TO_SINGLE_FILE         32793
#define ID_VIEW_SHOWTOOLBAR             32794
#define ID_VIEW_SHOWSTATUSLINE          32795
#define ID_VIEW_SHOWPLAYERBAR           32796
#define ID_VIEW_RELOADCD                32797
#define ID_VIEW_SELECTALLTRACKSFILES    32798
#define ID_ID3TAGS_SAVECUESHEET         32799
#define ID_SETTINGS_LOGGING             32800
#define ID_PLAY                         32802
#define ID_STOP                         32803
#define ID_NEXT                         32804
#define ID_PREVIOUS                     32805
#define ID_PAUSE                        32806
#define IDS_SHOW_PLAYER                 32807
#define ID_OPENEJECT                    32808
#define ID_BATCH_ALBUM                  32809
#define ID_BATCH_SINGLETRACKS           32810
#define ID_CHECKFORNEWVESION            32812
#define ID_VIEW_SHOWPRESETBAR           32814
#define ID_HELP_REPORTABUG              32815
#define ID_SAVEPRESET                   32817
#define ID_DELETEPRESET                 32818
#define ID_PRESETDROPDOWN               32819
#define ID_DATEI_VERZEICHNISHINZUFGEN   32820
#define ID_ADD_FILE                     40001
#define ID_EXIT                         40003
#define ID_TAGEDIT                      40004
#define ID_SETTINGS                     40005
#define ID_ABOUT                        40006
#define ID_PRESET                       40007
#define IDS_MAIN_ADDFILECD              40007
#define IDS_NOFILESSELECTED             40008
#define IDS_EMPTYLIST                   40009
#define IDS_MAIN_NOAUDIOCD              40010
#define ID_TOOLS_EDITID3TAG             40011
#define IDS_NOTRACKSSELECTED            40011
#define IDS_DATATRACK                   40012
#define IDS_DRIVENOTREADY               40013
#define ICD_CDDB_SETTINGS               40014
#define IDS_ERRTOC                      40014
#define ID_CDDB_READFROMREMOTECDDBSERVER 40015
#define IDS_MAIN_LIST_TITLE             40015
#define ID_PREFERENCES_TAGWRITERSETTINGS 40016
#define IDS_ENC_ID3FAILED               40016
#define ID_PREFERENCES_CDREADERSETTINGS 40017
#define IDS_ENC_WRITEID3                40017
#define IDC_ST_RESTORE                  40018
#define IDS_ENC_ID3INTERR               40018
#define IDC_ST_EXIT                     40019
#define ID_EDIT_ID3                     40020
#define IDS_ENC_LOGFAILED               40020
#define ID_ADD                          40021
#define IDS_ENC_FILEEXISTS              40021
#define ID_REMOVE                       40022
#define IDS_ENC_DENIEDOVWR              40022
#define IDS_ENC_ERRDIRCREATE            40023
#define IDS_ENC_TOOLTIP                 40024
#define IDS_ENC_INITERR                 40025
#define IDS_ENC_SUCCESS                 40026
#define IDS_ENC_PREPARING               40027
#define IDS_ENC_RIPPING                 40028
#define ID_PREFERENCES_PLUGINS          40028
#define IDS_ENC_RIPPERROR               40029
#define IDS_ENC_NUMERRORS               40030
#define IDS_ENC_VIEW_LOG_ERR            40031
#define IDS_ENC_VIEW_LOG                40032
#define IDS_ENC_FILE_XOFY               40033
#define ID_NEXT_DRIVE                   40033
#define IDS_ENC_TRACK_XOFY              40034
#define ID_CD2MP3                       40034
#define IDS_ENC_EXTRACT_TRACK           40035
#define ID_CD2WAV                       40035
#define IDS_ENC_JITTER_ERR              40036
#define ID_WAV2MP3                      40036
#define IDS_ENC_FINISHED                40037
#define ID_ENCODER                      40037
#define IDS_ENC_CLOSE_BTN               40038
#define ID_FREEDB                       40038
#define IDS_ENC_WRITE_M3U               40039
#define ID_REFRESH                      40039
#define IDS_ENC_SAVED_M3U               40040
#define ID_CDDBID3TAGS_READCDPLAYERINI  40040
#define IDS_ENC_FAILED_M3U              40041
#define ID_CDDBID3TAGS_READCDTEXT       40041
#define IDS_ENC_WAVE_ENC                40042
#define ID_CDDBID3TAGS_SAVETOCDPLAYERINI 40042
#define IDS_ENC_WAVE_FILES              40043
#define ID_POPUP_EDITID3TAG             40043
#define IDS_CDDB_ERR_CFGWRITE           40044
#define ID_POPUP_REMOVEFROMLIST         40044
#define IDS_CDDB_ERR_CFGREAD            40045
#define ID_POPUP_ADDTOLIST              40045
#define IDS_CDDB_ERR_WINSOCK            40046
#define IDS_CDDB_ERR                    40047
#define IDS_ENCODER_ERROR_INVALIDINPUTSTREAM 40048
#define IDS_CDDBONWAVERR                40049
#define IDS_ENCODER_ERROR_SAMPLERATEBITRATEMISMATCH 40049
#define IDS_MAIN_DATATRACK              40050
#define IDS_NOSELECTION                 40052
#define IDS_FILEOPENERR                 40057
#define IDS_INVBITRATE                  40058
#define IDS_RESTARTLAME                 40059
#define IDS_MAIN_AUDIOTRACK             40060
#define IDS_ENC_NO_PLUGIN               40061
#define IDS_ENC_PLUG_LOADFAILED         40062
#define IDS_ENC_PLUG_APIERROR           40063
#define IDS_TOOL_CD2MP3                 40064
#define IDS_TOOL_CD2WAV                 40065
#define IDS_TOOL_ANY2MP3                40066
#define IDS_TOOL_REFRESH                40067
#define IDS_TOOL_EJECT_ADD              40068
#define IDS_TOOL_CDPLAY                 40069
#define IDS_TOOL_CDSTOP                 40070
#define IDS_TOOL_CDPAUSE                40071
#define IDS_TOOL_CDPREV                 40072
#define IDS_TOOL_CDNEXT                 40073
#define IDS_TOOL_ENCODERSETT            40074
#define IDS_TOOL_LISTTITLE              40075
#define IDS_TOOL_QUERYCDDB              40076
#define IDS_TOOL_STARTENCODE            40077
#define IDS_TOOL_EDITID3                40078
#define IDS_CDPINI_ONLYCD               40079
#define IDS_CDPINI_NOENTRY              40080
#define IDS_CDPINI_ERRORWRITE           40081
#define IDS_CDPINI_DOUBLEENTRY          40082
#define IDS_CDPINI_WRITE_OK             40083
#define IDS_CDTEXT_ERROR                40084
#define IDS_DEFAULT_ARTIST              40085
#define IDS_DEFAULT_ALBUM               40086
#define IDS_TOOL_BEEP                   40087
#define IDS_TOOL_NOTIFICATION           40088
#define IDS_TOOL_M3U                    40089
#define IDS_TOOL_PLAYFILES              40090
#define IDS_TOOL_QUIT                   40091
#define IDS_TOOL_SHUTDOWN               40092
#define IDS_TOOL_SILENT                 40093
#define IDS_TOOL_OUTPUTPATH             40094
#define IDS_TOOL_EXTPLAYER              40095
#define IDS_TOOL_PLUGINPATH             40096
#define IDS_TOOL_READCDPINI             40097
#define IDS_TOOL_WRITECDPINI            40098
#define IDS_TOOL_CDTEXTREAD             40099
#define IDS_TOOL_DEFAULTDRIVE           40100
#define IDS_TOOL_CDROMTYPE              40101
#define IDS_TOOL_EJECTCD                40102
#define IDS_TOOL_LOCKDRIVE              40103
#define IDS_TOOL_RMETHOD                40104
#define IDS_TOOL_SELECT                 40105
#define IDS_TOOL_SWAPCHNL               40106
#define IDS_TOOL_SPINUP                 40107
#define IDS_TOOL_NTSCSI                 40108
#define IDS_TOOL_CDSPEED                40109
#define IDS_TOOL_CP                     40110
#define IDS_TOOL_CRC                    40111
#define IDS_TOOL_ORIG                   40112
#define IDS_TOOL_PRIVATE                40113
#define IDS_TOOL_CHANNELS               40114
#define IDS_TOOL_MINBITRATE             40115
#define IDS_TOOL_MAXBITRATE             40116
#define IDS_TOOL_ABR                    40117
#define IDS_TOOL_VBRMETHOD              40118
#define IDS_TOOL_VBRQUALITY             40119
#define IDS_TOOL_MPEGVER                40120
#define IDS_TOOL_FORMATSTR              40121
#define IDS_TOOL_WRITEID3               40122
#define IDS_TOOL_USEFORMATSTR           40123
#define IDS_TOOL_QUALPRESET             40124
#define IDS_ID3SETT_INV_FSTR            40125
#define IDS_PLUGIN_INSTALL              40126
#define IDS_PLUGIN_NOSEL                40127
#define IDS_PLUGIN_WINAMPDEINST         40128
#define IDS_PLUGIN_DEINST               40129
#define IDS_PLUGIN_DEINSTFAILED         40130
#define IDS_SETUP_NOWINAMP              40131
#define IDS_SETUP_FOUNDWINAMP           40132
#define IDS_ERR_LONGFILENAME            40133
#define IDS_ENC_DISCARD_LOG             40134
#define IDS_FDB_PROXYCONNECT            40135
#define IDS_FDB_SERVERCONNECT           40136
#define IDS_ERR_NOSERVERRESPONSE        40137
#define IDS_ERR_GETTRACKPOSFAILED       40138
#define IDS_FDB_NOENTRY                 40140
#define IDS_FDB_SELECTENTRY             40141
#define IDS_FDB_QUERYSTART              40142
#define IDS_FDB_TRACKUPDATE             40143
#define IDS_TOOL_PLAYSOUND              40144
#define IDS_TOOL_SAVEWINPOS             40145
#define IDS_TOOL_HIGHCOLOR              40146
#define IDS_TOOL_GETFOCUS               40147
#define IDS_TOOL_IDENTCOMB              40148
#define IDS_FDB_GETENTRIES              40149
#define IDS_ID3_CHOOSE_FILE             40150
#define IDS_CUESHEETSAVED               40151
#define IDS_CUESHEETFAILED              40152
#define IDS_SCSINOTSUPPORTED            40153
#define IDS_FAILEDLOADINGASPI           40154
#define IDS_FAILEDGETASPISTATUS         40155
#define IDS_FAILEDASPINOTSELECTED       40156
#define IDS_AUDIOFILEPLUGIN             40157
#define IDS_ERR_SHUTDOWN                40158
#define IDS_CDMODENODROP                40159
#define IDS_UNSUPPORTEDFILE             40160
#define IDS_TOOL_REPORTSTYLE            40161
#define IDS_TOOL_NEWLOGSTYLE            40162
#define IDS_TOOL_STARTSESSION           40163
#define IDS_TOOL_LOGENTRY               40164
#define IDS_TOOL_ENDSESSION             40165
#define IDS_LOGSAVEDSUCCESS             40166
#define IDS_TOOL_SHOWSPLASH             40167
#define IDS_TOOL_CONFIGUREIN            40168
#define IDS_TOOL_CONFIGUREOUT           40169
#define IDS_TOOL_INPUTDEVICE            40170
#define IDS_TOOL_OUTPUTDEVICE           40171
#define IDS_TOOL_ALWAYSTAGEDIT          40172
#define IDS_BKSLHWARN                   40173
#define IDS_DBLBACKSLASH                40174
#define IDS_CDDB_UPDATEDSERVERS         40175
#define IDS_CDDB_UPDATEFAILED           40176
#define IDS_OLDCOMTL32DLL               40177
#define IDS_BATCHNEXTCD                 40178
#define IDS_BATCHTIMEDOUT               40179
#define IDS_BATCHCDDRIVE                40180
#define IDS_TOOL_READBUFFERS            40181
#define IDS_TOOL_BATCHALLCDS            40182
#define IDS_TOOL_BATCHFREEDB            40183
#define IDS_TOOL_BATCHTIMESOUT          40184
#define IDS_TOOL_BATCHBEEP              40185
#define IDS_TOOL_BATCHTIME              40186
#define IDS_TOOL_ENCTHREADP             40187
#define IDS_TOOL_WRITECUE               40188
#define IDS_TOOL_HIDEMAINWND            40189
#define IDS_TOOL_ENQUEUE                40190
#define IDS_TOOL_FILEFORMAT             40191
#define IDS_LOG_STARTSESSION            40192
#define IDS_LOG_FINISHEDSESSION         40193
#define IDS_LOG_STARTFILE               40194
#define IDS_LOG_SAVEAS                  40195
#define IDS_LOG_FILEFORMAT              40196
#define IDS_LOG_FINISHEDFILE            40197
#define IDS_LOG_COLUMNCAPTION           40198
#define IDS_UPDATE_ERROR                40199
#define IDS_UPDATE_AVAILABLE            40200
#define IDS_UPDATE_NO                   40201
#define IDS_UPDATE_NOTQUERIED           40202
#define IDS_DEFAULTPRESETNOTREMOVABLE   61204
#define IDS_COULDNOTREMOVEPRESET        61205
#define IDS_ERRPRESETCREATE             61206
#define IDS_PRESET_INVALIDNAME          61207
#define IDS_PRESET_NAMENOTALLOWED       61208
#define IDS_TOOL_DEFAULTCD              61209
#define IDS_TOOL_DEFAULTFILE            61210
#define IDS_TOOL_LASTDECODER            61211
#define IDS_TOOL_LASTENCODER            61212
#define IDS_TOOL_SHOWID3FILE            61213
#define IDS_TOOL_CHECKNEWCD             61214
#define IDS_TOOL_BATCHAPPENDDISCID      61215
#define IDS_TOOL_MP3OUTSAMPLE           61216
#define IDS_TOOL_ID3V1                  61217
#define IDS_TOOL_FDBAUTH                61218
#define IDS_TOOL_FDBPASS                61219
#define IDS_TOOL_FDBPROXYADD            61220
#define IDS_TOOL_FDBPROXYPORT           61221
#define IDS_TOOL_FDBSERVER              61222
#define IDS_TOOL_FDBUSEPROXY            61223
#define IDS_TOOL_FDBUSER                61224
#define IDS_TOOL_FDBMAIL                61225
#define IDS_TOOL_FDBTIMEOUT             61226

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1131
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
