//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by lameFE.rc
//
#define MANIFEST_RESOURCE_ID            2
#define IDD_ABOUTBOX                    100
#define IDD_SETTINGS_I18N               101
#define IDD_ALBUMINFOCTRL               103
#define IDD_ENCODER_PAGE                107
#define IDD_SETTINGS_MP3                107
#define IDD_FILENAMES                   108
#define IDR_MAINFRAME                   128
#define IDD_PRESETBAR                   128
#define IDR_LAMEFETYPE                  129
#define IDR_MAIN_MENU                   129
#define IDS_THREADWARNING               129
#define IDD_FREEDB_QUERY                130
#define IDS_APPALREADYRUNNING           130
#define IDI_NEXT                        131
#define IDS_DECODER                     131
#define IDI_STOP                        132
#define IDS_ENCODER                     132
#define IDI_EJECT                       133
#define IDS_ALBUMINFO                   133
#define IDI_PREV                        134
#define IDD_PRESET                      134
#define IDS_BATCHMODE                   134
#define IDI_PLAY                        135
#define IDS_FILENAMES                   135
#define IDI_PAUSE                       136
#define IDS_LOOKNFEEL                   136
#define IDB_SPLASH                      137
#define IDS_NONESELECTED                137
#define IDS_PRESET_BLANKNAME            138
#define IDB_FREEDB                      139
#define IDD_SETTINGS                    139
#define IDD_SETTINGS_FILENAMES          139
#define IDD_ID3EDIT                     140
#define IDD_STATUS_DIALOG               142
#define IDR_CD_PLAYER                   144
#define IDD_TRACKLIST                   146
#define IDI_CONFIG_OUT                  151
#define IDI_CONFIG_IN                   152
#define IDB_IMAGES                      153
#define IDB_TOOLBAR_HI                  154
#define IDD_SETTINGS_CDRIPPER           155
#define IDD_PATH_AND_FILENAMES          156
#define IDB_LIST_BK                     159
#define IDB_LOG_IMAGES                  162
#define IDR_FINISHED                    163
#define IDB_TOOLBAR_HI_DEACT            164
#define IDD_LAMEFE_PAGE                 165
#define IDD_CDRIP_PAGE                  166
#define IDD_CDDB_QUERY                  167
#define IDD_SETTINGS_FREEDB             168
#define IDR_SYSTRAY_MENU                169
#define IDR_INT_PLAYER                  170
#define IDD_SETTINGSDIALOG              171
#define IDB_SETTINGS_IMAGES             172
#define IDD_SETTINGS_LAMEFE             173
#define IDD_CHECKNEWVERSION             174
#define IDD_SETTINGS_LOOKNFEEL          175
#define IDD_SETTINGS_BATCHMODE          176
#define IDD_SETTINGS_PLUGINCODEC        177
#define IDI_ENCODER                     178
#define IDI_DECODER                     179
#define IDR_MAINFRAMESMALL              180
#define IDD_PLUGINPAGE                  181
#define IDB_MENUITEMS                   182
#define IDB_TOOLBAR_2_HI                182
#define IDD_SETTINGS_DECODER            183
#define IDR_PRESETBAR_2                 184
#define SPLASH                          185
#define IDD_SAVEPRESET                  186
#define IDD_SETUPWIZARD                 187
#define IDR_LIST_MENU                   188
#define IDD_FREEDB_STATUS               189
#define IDB_FREEDBLOGO                  190
#define IDR_CONTROLBAR                  191
#define IDR_CONTEXTMENU_LIST            193
#define IDR_TAGEDIT_MENU                194
#define IDD_OVERWRITEWARNING            195
#define IDD_CDROM_AUTODETEC             196
#define IDC_INPUT_DEVICE                1001
#define IDC_PRESET                      1002
#define IDC_OUTPUT_DEVICE               1003
#define IDC_PROTOCOLL                   1004
#define IDC_START                       1005
#define IDC_LIST                        1006
#define IDC_ENCODE                      1007
#define IDC_STATIC_1                    1008
#define IDC_STATIC_2                    1009
#define IDC_ENCODING                    1010
#define IDC_SAMPLES                     1011
#define IDC_BITRATE                     1012
#define IDC_CONFIGURE_OUT               1013
#define IDC_ABOUT_OUT                   1014
#define IDC_ORIG                        1015
#define IDC_COPY                        1016
#define IDC_CONFIG_OUT                  1017
#define IDC_SAVE                        1018
#define IDC_CONFIG_IN                   1019
#define IDC_FILENAME_VIS                1021
#define IDC_DELETE                      1022
#define IDC_ALBUM_MODE_FILENAME         1023
#define IDC_PROGRESS_FILE               1024
#define IDC_PLAYLIST_FILENAME           1025
#define IDC_PROGRESS_LIST               1026
#define IDC_PLAYLIST_VIS                1027
#define IDC_ALBUM_MODE_VIS              1028
#define IDC_STATUS                      1029
#define IDC_START_SESSION               1031
#define IDC_LOG_ENTRY                   1032
#define IDC_END_SESSION                 1033
#define IDC_LOG                         1034
#define IDC_REPORT_STYLE                1035
#define IDC_REAL_TIME_LOG               1036
#define IDC_SAVE_LOG                    1037
#define IDC_PRINT                       1038
#define IDC_FOCUS                       1039
#define IDC_PLAY_SOUND                  1040
#define IDC_BEEP                        1041
#define IDC_PLAY                        1042
#define IDC_SAVE_WINDOW_STATE           1043
#define IDC_M3U                         1044
#define IDC_DLG                         1045
#define IDC_USE_HIGH_COLOR_ICONS        1046
#define IDC_PATHCHK                     1047
#define IDC_CONVERTTO16BIT              1048
#define IDC_ID3V1                       1049
#define IDC_PRINTMSG                    1050
#define IDC_PLAYER                      1051
#define IDC_STATUS_STRING               1052
#define IDC_STRPLAYER                   1053
#define IDC_PLAYER2                     1054
#define IDC_SHOW_SPLASH                 1055
#define IDC_LAMEVERSION                 1056
#define IDC_SONGTITLE                   1057
#define IDC_FILES                       1058
#define IDC_SONGINTERPRET               1059
#define IDC_ALBUMNAME                   1061
#define IDC_ARTIST                      1062
#define IDC_ALBUM                       1063
#define IDC_TRACKNUMBER                 1064
#define IDC_COMMENT                     1065
#define IDC_YEAR                        1066
#define IDC_TRACK                       1067
#define IDC_FILEN                       1068
#define IDC_RENAME                      1069
#define IDC_GENRE                       1070
#define IDC_SAVE_PATH                   1071
#define IDC_LIST_STATUS_BAR             1072
#define IDC_LIST_STATUS_BAR2            1073
#define IDC_ALBUMINFO_CTRL              1074
#define IDC_SEL_ID3V2                   1075
#define IDC_IN_SIZE                     1076
#define IDC_FILE_STATUS_BAR             1077
#define IDC_FILE_X_OF_Y                 1078
#define IDC_ERRORS                      1079
#define IDC_OUTPUTPATH                  1080
#define IDC_LIST_MSG                    1081
#define IDC_FILE_MSG                    1082
#define IDC_IN                          1083
#define IDC_OUT                         1084
#define IDC_ID3_TAG                     1085
#define IDC_PRESETS                     1086
#define IDC_COMBO2                      1087
#define IDC_THREADPRIORITY              1088
#define IDC_HIDEMWND_ENC                1089
#define IDC_SONG_A                      1090
#define IDC_BATCH_FREEDB                1091
#define IDC_ARTIST_A                    1092
#define IDC_BATCHTIMEOUT                1093
#define IDC_ALBUM_A                     1094
#define IDC_BATCH_TIMEOUTEDIT           1095
#define IDC_COMMENT_A                   1096
#define IDC_BATCHALLDRIVES              1097
#define IDC_GENRE_A                     1098
#define IDC_YEAR_A                      1099
#define IDC_NUMBUFFERS                  1100
#define IDC_CHECK3                      1101
#define IDC_CHECKFORNEWCD               1102
#define IDC_SHOW_TAGEDITOR_ONFILE       1103
#define IDC_TRACK_A                     1104
#define IDC_APPENDDISCID                1105
#define IDC_AM_ARTIST                   1106
#define IDC_MODULES                     1107
#define IDC_AM_ALBUM                    1108
#define IDC_AM_GENRE                    1109
#define IDC_AM_COMMENT                  1110
#define IDC_YOUR_VERSION                1111
#define IDC_AM_YEAR                     1112
#define IDC_NEWESTVERSION               1113
#define IDC_MESSAGE_VERSION             1114
#define IDC_FILE_NAME                   1115
#define IDC_DOWNLOAD                    1116
#define IDC_PLACEHOLDER_STATIC          1117
#define IDC_EXTENSIONS                  1118
#define IDC_ABOUTSTRING                 1119
#define IDC_ABOUT                       1120
#define IDC_ID3TAG                      1121
#define IDC_CONFIGURATION               1122
#define IDC_ALBUM_MODE                  1123
#define IDC_PLUGINNAME                  1124
#define IDC_CHANGELOG                   1125
#define IDC_APPLY                       1126
#define IDC_PRESETMP3DLG                1127
#define IDC_SAVEPRESET                  1128
#define IDC_SELECTPRESET                1129
#define IDC_REFRESH                     1130
#define IDC_PRESETDESCRIPTION           1131
#define IDC_PRESETPATH                  1132
#define IDC_DEFAULT_FILE                1133
#define IDC_PRESET_PATH_DISPLAY         1134
#define IDC_WINAMP_PATH                 1135
#define IDC_PATH_WINAMP                 1136
#define IDC_OUTSAMPLERATE               1137
#define IDC_REMEMBERLASTENCODER         1138
#define IDC_EJECT_CD                    1139
#define IDC_PRESETNAME                  1140
#define IDC_PRESETCOMMENT               1141
#define IDC_ENCODER_VERSION             1142
#define IDC_REMEMBER_LAST               1143
#define IDC_LANGNAME                    1144
#define IDC_BITSPERSAMPLE               1145
#define IDC_LANGCODEPG                  1146
#define IDC_CHANNELS                    1147
#define IDC_L                           1148
#define IDC_STATIC_LANGAUTHOR           1149
#define IDC_BITSPERSAMPLE_MAX           1150
#define IDC_LANGAUTHOR                  1151
#define IDC_COPYRIGHT                   1152
#define IDC_ORIGINAL                    1153
#define IDC_CHECKSUM                    1154
#define IDC_PRIVATE                     1155
#define IDC_ID3_2                       1156
#define IDC_OUTPUT                      1157
#define IDC_PLAYER_PATH                 1158
#define IDC_OUTPUT_PATH                 1159
#define IDC_FINISH_DLG                  1160
#define IDC_PLAY_FILES                  1161
#define IDC_SHUTDOWN                    1162
#define IDC_EXIT_FINISHED               1163
#define IDC_CD_DRIVE                    1164
#define IDC_CDROM_TYPE                  1165
#define IDC_RIPPING_METHOD              1166
#define IDC_EJECT                       1167
#define IDC_LOCK                        1168
#define IDC_SWAP                        1169
#define IDC_REMOTE_SERVER               1170
#define IDC_LOCATION                    1171
#define IDC_ADDRESS                     1172
#define IDC_PATH                        1173
#define IDC_REMOTE_PORT                 1174
#define IDC_EMAIL                       1175
#define IDC_TIMEOUT                     1176
#define IDC_PROXY                       1177
#define IDC_USE_PROXY                   1178
#define IDC_PROXY_PORT                  1179
#define IDC_USERNAME                    1180
#define IDC_PASSWORD                    1181
#define IDC_Version                     1182
#define IDC_CD_SPEED                    1183
#define IDC_CD_SPIN_UP                  1184
#define IDC_NATIVE                      1185
#define IDC_AUTHENTICATION              1186
#define IDC_UPDATE                      1187
#define IDC_CDDB                        1188
#define IDC_SELECT_ALL                  1190
#define IDC_EST_TIME                    1191
#define IDC_ELA_TIME                    1192
#define IDC_REM_TIME                    1193
#define IDC_MPEG                        1194
#define IDC_FORMAT                      1195
#define IDC_SUBDIR                      1196
#define IDC_SILENT                      1197
#define IDC_LIST_TITLE                  1198
#define IDC_PLUGINS                     1199
#define IDC_PLUGINPATH                  1200
#define IDC_INSTALLED_PLUGINS           1201
#define IDC_CONFIGURE                   1202
#define IDC_INSTALL                     1203
#define IDC_UNINSTALL                   1204
#define IDC_DISPLAY_STATIC              1205
#define IDC_JITTERSTATUS                1206
#define IDC_DEFAULTPLAYER               1207
#define IDC_CHANGE_PLAYER               1208
#define IDC_PATH2PLAYER                 1209
#define IDC_DEFAULT_CD                  1210
#define IDC_PLUGIN_DETAILS              1211
#define IDC_ABOUT_PLUGIN                1212
#define IDC_QUALITY                     1213
#define IDC_VBR_METHOD                  1214
#define IDC_ABR                         1215
#define IDC_VBR_QUALITY                 1216
#define IDC_OUT_PLUGINS                 1217
#define IDC_FILES_TRACKS                1218
#define IDC_LANGUAGELIST                1219
#define IDC_CPLAYERINI_ALWAYS_READ      1220
#define IDC_SEL_ID3V1                   1221
#define IDC_CPLAYERINI_ALWAYS_WRITE     1222
#define IDC_CDTEXT_ALWAYSREAD           1223
#define IDC_USE_LAMEFE                  1224
#define IDC_USE_WINAMP                  1225
#define IDC_STATUS_MSG                  1226
#define IDC_ENQUEUE_FILES               1227
#define IDC_STATIC_INTERPRET            1228
#define IDC_STATIC_TRACK                1229
#define IDC_STATIC_ALBUM                1230
#define IDC_STATIC_GENRE                1231
#define IDC_STATIC_YEAR                 1232
#define IDC_STATIC_COMMENT              1233
#define IDC_STATIC_SONGTITLE            1234
#define IDC_STATIC_FREEDBENTRIES        1235
#define IDC_STATIC_SELECTFDB            1236
#define IDC_STATIC_CHECKUPDATE          1237
#define IDC_STATIC_INSTALLEDVER         1238
#define IDC_STATIC_NEWESTVER            1239
#define IDC_STATIC_FDBMESSAGE           1240
#define IDC_STATIC_CDDBBYFREEDB         1241
#define IDC_STATIC_ENTERNAME            1242
#define IDC_STATIC_PRSTCOMMENT          1243
#define IDC_STATIC_BATCHMODE            1244
#define IDC_STATIC_CDRIPDLL             1245
#define IDC_STATIC_CDADVANCED           1246
#define IDC_STATIC_BUFFEREXPL           1247
#define IDC_STATIC_NUMBUFFERS           1248
#define IDC_STATIC_DEFAULTDEC           1249
#define IDC_STATIC_DECEXPL              1250
#define IDC_STATIC_DECWINAMP            1251
#define IDC_STATIC_WINAMPEXPL           1252
#define IDC_STATIC_WINAMPEXPL2          1253
#define IDC_STATIC_BASEPATH             1254
#define IDC_STATIC_PATHEXPL             1255
#define IDC_STATIC_FILENAME             1256
#define IDC_STATIC_PREVIEW              1257
#define IDC_STATIC_PREVIEW2             1258
#define IDC_STATIC_PREVIEW3             1259
#define IDC_STATIC_ALBUMMODE            1260
#define IDC_STATIC_PLAYLIST             1261
#define IDC_STATIC_SERVERRECT           1262
#define IDC_STATIC_SERVER               1263
#define IDC_STATIC_LOCATION             1264
#define IDC_STATIC_ADDRESS              1265
#define IDC_STATIC_PATH                 1266
#define IDC_STATIC_PORT                 1267
#define IDC_STATIC_TIMEOUT              1268
#define IDC_STATIC_EMAIL                1269
#define IDC_STATIC_PROXYRECT            1270
#define IDC_STATIC_PROXYPORT            1271
#define IDC_STATIC_USERNAME             1272
#define IDC_STATIC_PASSWORD             1273
#define IDC_STATIC_LANGRECT             1274
#define IDC_STATIC_LANGDET              1275
#define IDC_STATIC_LANGNAME             1276
#define IDC_STATIC_CODEPAGE             1278
#define IDC_STATIC_EXTPLAYER            1279
#define IDC_STATIC_PRESETPATH           1280
#define IDC_STATIC_TODORECT             1281
#define IDC_STATIC_MISCRECT             1282
#define IDC_STATIC_LOOKNFEEL            1283
#define IDC_STATIC_MP3DLL               1284
#define IDC_STATIC_ID3                  1285
#define IDC_STATIC_SPEED                1286
#define IDC_STATIC_PLUGINFO             1287
#define IDC_STATIC_PLUGFORMAT           1288
#define IDC_STATIC_PLUGCONF             1289
#define IDC_STATIC_READRECT             1290
#define IDC_STATIC_MAX                  1291
#define IDC_STATIC_NOMINAL              1292
#define IDC_STATIC_MIN                  1293
#define IDC_STATIC_EMPTY                1294
#define IDC_STATIC_FULL                 1295
#define IDC_STATIC_JITTERSTATUS         1296
#define IDC_STATIC_BUFFERSTATUS         1297
#define IDC_STATIC_FILERECT             1298
#define IDC_STATIC_ORGFILE              1299
#define IDC_STATIC_OUTFILE              1300
#define IDC_STATIC_SIZE1                1301
#define IDC_STATIC_SIZE2                1302
#define IDC_STATIC_ESTTIME              1303
#define IDC_STATIC_ELATIME              1304
#define IDC_STATIC_REMTIME              1305
#define IDC_STATIC_CHANGELOG            1306
#define IDC_STATIC_ENCODEDBY            1307
#define IDC_ENCODEDBY                   1308
#define IDC_PICUTRE_PATH                1309
#define IDC_STATIC_PICTURE              1310
#define IDC_BROWSE_PICTURE              1311
#define IDC_STATIC_MAXPICSIZE           1312
#define IDC_CUE                         1313
#define IDC_EST_SIZE                    1314
#define IDC_CHECK2                      1315
#define IDC_ALBUMEDIT                   1316
#define IDC_BATCH_BEEP                  1317
#define IDC_EMPTY_TAG                   1320
#define IDC_CASE                        1321
#define IDC_SWAP_TITELINTERPRET         1322
#define IDC_READ_SECTORS                1324
#define IDC_READ_OVERLAP                1325
#define IDC_NUMBER_RETRIES              1326
#define IDC_START_OFFSET                1327
#define IDC_END_OFFSET                  1328
#define IDC_BLOCK_COMPARE               1329
#define IDC_AUTODETECT                  1330
#define IDC_STATIC_READSECTORS          1331
#define IDC_STATIC_READOVERLAP          1332
#define IDC_STATIC_STARTOFFSET          1333
#define IDC_STATIC_ENDOFFSET            1334
#define IDC_STATIC_CDROMTYPE            1335
#define IDC_STATIC_RIPPING_METHOD       1336
#define IDC_STATIC_SPINUPTIME           1337
#define IDC_STATIC_CDSPEED              1338
#define IDC_STATIC_BLOCKCOMPARE         1339
#define IDC_STATIC_NUMRETRUES           1340
#define IDC_STATIC_CDROM                1341
#define IDC_OVERWRITE                   1342
#define IDC_NOOVERWRITE                 1343
#define IDC_ALL_YES                     1344
#define IDC_NO_ALL                      1345
#define IDC_STATIC_FILEEXISTS           1346
#define ID_CLOSE                        1347
#define ID_CHECKNOW                     1348
#define ID_SAVE                         1349
#define IDC_ENABLEJITTERCORRECTION      1350
#define IDC_ABORT                       1351
#define IDC_STATIC_AUTODETECT_MMCSTATUS 1352
#define IDC_MMCSTATUS                   1353
#define IDC_STATIC_AUTODETECT_LISTDESCRIPTION 1354
#define IDC_TWO_PHASE_EXTRACTION        1366
#define IDC_STATIC_BATCHSCRIPT          1367
#define IDC_ACTIVE_COMMANDS             1368
#define IDC_AVAILABLE_COMMANDS          1369
#define IDC_ADD_COMMAND                 1370
#define IDC_REMOVE_COMMAND              1371
#define IDC_COMMAND_UP                  1372
#define IDC_COMMAND_DOWN                1373
#define IDC_STATIC_AVAILABLE_CMDS       1374
#define IDC_STATUS_STRING_PHASE2        1375
#define IDC_FILE_STATUSBAR_PHASE2       1376
#define IDC_STATIC_TEMPPATH             1377
#define IDC_TEMPPATH_DISPLAY            1378
#define IDC_TEMPPATH                    1379
#define IDC_STATIC_2PHASE_0             1380
#define IDC_STATIC_2PHASE_100           1381
#define ID_REMOVE_FILE                  32771
#define ID_HELP_HELPINDEX               32772
#define ID_HELP_LICENSE                 32773
#define ID_ID3TAGS_READFREEDBSERVER     32774
#define ID_ID3TAGS_READCDTEXT           32775
#define ID_ID3TAGS_READCDPLAYERINI      32776
#define ID_ID3TAGS_SAVETOCDPLAYERINI    32777
#define ID_ID3TAGS_ID3TAGEDITOR         32778
#define ID_SETTINGS_CDREADER            32779
#define ID_SETTINGS_PLUGINS             32780
#define ID_SETTINGS_PREFERENCES         32781
#define ID_SETTINGS_LAMEENCODER         32782
#define ID_SETTINGS_ID3TAGSFILENAMES    32783
#define ID_FILE_REMOVE                  32784
#define ID_SETTINGS_FREEDBSETUP         32791
#define ID_FILE_STARTENCODING           32792
#define ID_START_TO_SINGLE_FILE         32793
#define ID_VIEW_SHOWTOOLBAR             32794
#define ID_VIEW_SHOWSTATUSLINE          32795
#define ID_VIEW_SHOWPLAYERBAR           32796
#define ID_VIEW_RELOADCD                32797
#define ID_VIEW_SELECTALLTRACKSFILES    32798
#define ID_ID3TAGS_SAVECUESHEET         32799
#define ID_SETTINGS_LOGGING             32800
#define ID_PRESET                       32801
#define ID_PLAY                         32802
#define ID_STOP                         32803
#define ID_NEXT                         32804
#define ID_PREVIOUS                     32805
#define ID_PAUSE                        32806
#define IDS_SHOW_PLAYER                 32807
#define ID_OPENEJECT                    32808
#define ID_BATCH_ALBUM                  32809
#define ID_BATCH_SINGLETRACKS           32810
#define ID_CHECKFORNEWVESION            32812
#define ID_VIEW_SHOWPRESETBAR           32814
#define ID_HELP_REPORTABUG              32815
#define ID_SAVEPRESET                   32817
#define ID_DELETEPRESET                 32818
#define ID_PRESETDROPDOWN               32819
#define ID_ADD_FILE                     40001
#define ID_EXIT                         40003
#define ID_TAGEDIT                      40004
#define ID_SETTINGS                     40005
#define ID_ABOUT                        40006
#define IDS_MAIN_ADDFILECD              40007
#define IDS_NOFILESSELECTED             40008
#define IDS_EMPTYLIST                   40009
#define IDS_MAIN_NOAUDIOCD              40010
#define ID_TOOLS_EDITID3TAG             40011
#define IDS_DATATRACK                   40012
#define IDS_DRIVENOTREADY               40013
#define ICD_CDDB_SETTINGS               40014
#define IDS_ERRTOC                      40015
#define IDS_MAIN_LIST_TITLE             40016
#define ID_PREFERENCES_TAGWRITERSETTINGS 40017
#define IDS_ENC_WRITEID3                40018
#define IDC_ST_RESTORE                  40019
#define IDC_ST_EXIT                     40020
#define ID_EDIT_ID3                     40021
#define IDS_ENC_LOGFAILED               40022
#define ID_ADD                          40023
#define IDS_ENC_FILEEXISTS              40024
#define ID_REMOVE                       40025
#define IDS_ENC_DENIEDOVWR              40026
#define IDS_ENC_ERRDIRCREATE            40027
#define IDS_ENC_TOOLTIP                 40028
#define IDS_ENC_INITERR                 40029
#define IDS_ENC_SUCCESS                 40030
#define IDS_ENC_PREPARING               40031
#define IDS_ENC_RIPPING                 40032
#define ID_PREFERENCES_PLUGINS          40033
#define IDS_ENC_RIPPERROR               40034
#define IDS_ENC_NUMERRORS               40035
#define IDS_ENC_VIEW_LOG_ERR            40036
#define IDS_ENC_VIEW_LOG                40037
#define IDS_ENC_FILE_XOFY               40038
#define ID_NEXT_DRIVE                   40039
#define IDS_ENC_TRACK_XOFY              40040
#define ID_CD2MP3                       40041
#define IDS_ENC_EXTRACT_TRACK           40042
#define ID_CD2WAV                       40043
#define IDS_ENC_JITTER_ERR              40044
#define ID_WAV2MP3                      40045
#define IDS_ENC_FINISHED                40046
#define ID_ENCODER                      40047
#define IDS_ENC_CLOSE_BTN               40048
#define ID_FREEDB                       40049
#define IDS_ENC_WRITE_M3U               40050
#define ID_REFRESH                      40051
#define IDS_ENC_SAVED_M3U               40052
#define ID_CDDBID3TAGS_READCDPLAYERINI  40053
#define IDS_ENC_FAILED_M3U              40054
#define ID_CDDBID3TAGS_READCDTEXT       40055
#define IDS_ENC_WAVE_ENC                40056
#define ID_CDDBID3TAGS_SAVETOCDPLAYERINI 40057
#define IDS_ENC_WAVE_FILES              40058
#define ID_POPUP_EDITID3TAG             40059
#define IDS_CDDB_ERR_CFGWRITE           40060
#define ID_POPUP_REMOVEFROMLIST         40061
#define IDS_CDDB_ERR_CFGREAD            40062
#define ID_POPUP_ADDTOLIST              40063
#define IDS_CDDB_ERR_WINSOCK            40064
#define IDS_CDDB_ERR                    40065
#define IDS_ENCODER_ERROR_INVALIDINPUTSTREAM 40066
#define IDS_CDDBONWAVERR                40067
#define IDS_ENCODER_ERROR_SAMPLERATEBITRATEMISMATCH 40068
#define IDS_MAIN_DATATRACK              40069
#define IDS_NOSELECTION                 40070
#define IDS_FILEOPENERR                 40071
#define IDS_INVBITRATE                  40072
#define IDS_RESTARTLAME                 40073
#define IDS_MAIN_AUDIOTRACK             40074
#define IDS_ENC_NO_PLUGIN               40075
#define IDS_ENC_PLUG_LOADFAILED         40076
#define IDS_ENC_PLUG_APIERROR           40077
#define IDS_TOOL_CD2MP3                 40078
#define IDS_TOOL_CD2WAV                 40079
#define IDS_TOOL_ANY2MP3                40080
#define IDS_TOOL_REFRESH                40081
#define IDS_TOOL_EJECT_ADD              40082
#define IDS_TOOL_CDPLAY                 40083
#define IDS_TOOL_CDSTOP                 40084
#define IDS_TOOL_CDPAUSE                40085
#define IDS_TOOL_CDPREV                 40086
#define IDS_TOOL_CDNEXT                 40087
#define IDS_TOOL_ENCODERSETT            40088
#define IDS_TOOL_LISTTITLE              40089
#define IDS_TOOL_QUERYCDDB              40090
#define IDS_TOOL_STARTENCODE            40091
#define IDS_TOOL_EDITID3                40092
#define IDS_CDPINI_ONLYCD               40093
#define IDS_CDPINI_NOENTRY              40094
#define IDS_CDPINI_ERRORWRITE           40095
#define IDS_CDPINI_DOUBLEENTRY          40096
#define IDS_CDPINI_WRITE_OK             40097
#define IDS_CDTEXT_ERROR                40098
#define IDS_DEFAULT_ARTIST              40099
#define IDS_DEFAULT_ALBUM               40100
#define IDS_TOOL_BEEP                   40101
#define IDS_TOOL_NOTIFICATION           40102
#define IDS_TOOL_M3U                    40103
#define IDS_TOOL_PLAYFILES              40104
#define IDS_TOOL_QUIT                   40105
#define IDS_TOOL_SHUTDOWN               40106
#define IDS_TOOL_SILENT                 40107
#define IDS_TOOL_OUTPUTPATH             40108
#define IDS_TOOL_EXTPLAYER              40109
#define IDS_TOOL_PLUGINPATH             40110
#define IDS_TOOL_READCDPINI             40111
#define IDS_TOOL_WRITECDPINI            40112
#define IDS_TOOL_CDTEXTREAD             40113
#define IDS_TOOL_DEFAULTDRIVE           40114
#define IDS_TOOL_CDROMTYPE              40115
#define IDS_TOOL_EJECTCD                40116
#define IDS_TOOL_LOCKDRIVE              40117
#define IDS_TOOL_RMETHOD                40118
#define IDS_TOOL_SELECT                 40119
#define IDS_TOOL_SWAPCHNL               40120
#define IDS_TOOL_SPINUP                 40121
#define IDS_TOOL_NTSCSI                 40122
#define IDS_TOOL_CDSPEED                40123
#define IDS_TOOL_CP                     40124
#define IDS_TOOL_CRC                    40125
#define IDS_TOOL_ORIG                   40126
#define IDS_TOOL_PRIVATE                40127
#define IDS_TOOL_CHANNELS               40128
#define IDS_TOOL_MINBITRATE             40129
#define IDS_TOOL_MAXBITRATE             40130
#define IDS_TOOL_ABR                    40131
#define IDS_TOOL_VBRMETHOD              40132
#define IDS_TOOL_VBRQUALITY             40133
#define IDS_TOOL_MPEGVER                40134
#define IDS_TOOL_FORMATSTR              40135
#define IDS_TOOL_WRITEID3               40136
#define IDS_TOOL_USEFORMATSTR           40137
#define IDS_TOOL_QUALPRESET             40138
#define IDS_ID3SETT_INV_FSTR            40139
#define IDS_PLUGIN_INSTALL              40140
#define IDS_PLUGIN_NOSEL                40141
#define IDS_PLUGIN_WINAMPDEINST         40142
#define IDS_PLUGIN_DEINST               40143
#define IDS_PLUGIN_DEINSTFAILED         40144
#define IDS_SETUP_NOWINAMP              40145
#define IDS_SETUP_FOUNDWINAMP           40146
#define IDS_ERR_LONGFILENAME            40147
#define IDS_ENC_DISCARD_LOG             40148
#define IDS_FDB_PROXYCONNECT            40149
#define IDS_FDB_SERVERCONNECT           40150
#define IDS_ERR_NOSERVERRESPONSE        40151
#define IDS_ERR_GETTRACKPOSFAILED       40152
#define IDS_FDB_NOENTRY                 40153
#define IDS_FDB_SELECTENTRY             40154
#define IDS_FDB_QUERYSTART              40155
#define IDS_FDB_TRACKUPDATE             40156
#define IDS_TOOL_PLAYSOUND              40157
#define IDS_TOOL_SAVEWINPOS             40158
#define IDS_TOOL_HIGHCOLOR              40159
#define IDS_TOOL_GETFOCUS               40160
#define IDS_TOOL_IDENTCOMB              40161
#define IDS_FDB_GETENTRIES              40162
#define IDS_ID3_CHOOSE_FILE             40163
#define IDS_CUESHEETSAVED               40164
#define IDS_CUESHEETFAILED              40165
#define IDS_SCSINOTSUPPORTED            40166
#define IDS_FAILEDLOADINGASPI           40167
#define IDS_FAILEDGETASPISTATUS         40168
#define IDS_FAILEDASPINOTSELECTED       40169
#define IDS_AUDIOFILEPLUGIN             40170
#define IDS_ERR_SHUTDOWN                40171
#define IDS_CDMODENODROP                40172
#define IDS_UNSUPPORTEDFILE             40173
#define IDS_TOOL_REPORTSTYLE            40174
#define IDS_FDB_INITWINSOCK             40174
#define IDS_TOOL_NEWLOGSTYLE            40175
#define IDS_TOOL_STARTSESSION           40176
#define IDS_TOOL_LOGENTRY               40177
#define IDS_TOOL_ENDSESSION             40178
#define IDS_LOGSAVEDSUCCESS             40179
#define IDS_TOOL_SHOWSPLASH             40180
#define IDS_TOOL_CONFIGUREIN            40181
#define IDS_TOOL_CONFIGUREOUT           40182
#define IDS_TOOL_INPUTDEVICE            40183
#define IDS_TOOL_OUTPUTDEVICE           40184
#define IDS_TOOL_ALWAYSTAGEDIT          40185
#define IDS_BKSLHWARN                   40186
#define IDS_DBLBACKSLASH                40187
#define IDS_CDDB_UPDATEDSERVERS         40188
#define IDS_CDDB_UPDATEFAILED           40189
#define IDS_OLDCOMTL32DLL               40190
#define IDS_BATCHNEXTCD                 40191
#define IDS_BATCHTIMEDOUT               40192
#define IDS_BATCHCDDRIVE                40193
#define IDS_TOOL_READBUFFERS            40194
#define IDS_TOOL_BATCHALLCDS            40195
#define IDS_TOOL_BATCHFREEDB            40196
#define IDS_TOOL_BATCHTIMESOUT          40197
#define IDS_TOOL_BATCHBEEP              40198
#define IDS_TOOL_BATCHTIME              40199
#define IDS_TOOL_ENCTHREADP             40200
#define IDS_TOOL_WRITECUE               40201
#define IDS_TOOL_HIDEMAINWND            40202
#define IDS_TOOL_ENQUEUE                40203
#define IDS_TOOL_FILEFORMAT             40204
#define IDS_LOG_STARTSESSION            40205
#define IDS_LOG_FINISHEDSESSION         40206
#define IDS_LOG_STARTFILE               40207
#define IDS_LOG_SAVEAS                  40208
#define IDS_LOG_FILEFORMAT              40209
#define IDS_LOG_FINISHEDFILE            40210
#define IDS_LOG_COLUMNCAPTION           40211
#define IDS_UPDATE_ERROR                40212
#define IDS_UPDATE_AVAILABLE            40213
#define IDS_UPDATE_NO                   40214
#define IDS_UPDATE_NOTQUERIED           40215
#define IDS_DEFAULTPRESETNOTREMOVABLE   40216
#define IDS_COULDNOTREMOVEPRESET        40217
#define IDS_ERRPRESETCREATE             40218
#define IDS_PRESET_INVALIDNAME          40219
#define IDS_PRESET_NAMENOTALLOWED       40220
#define IDS_TOOL_DEFAULTCD              40221
#define IDS_TOOL_DEFAULTFILE            40222
#define IDS_TOOL_LASTDECODER            40223
#define IDS_TOOL_LASTENCODER            40224
#define IDS_TOOL_SHOWID3FILE            40225
#define IDS_TOOL_CHECKNEWCD             40226
#define IDS_TOOL_BATCHAPPENDDISCID      40227
#define IDS_TOOL_MP3OUTSAMPLE           40228
#define IDS_TOOL_ID3V1                  40229
#define IDS_TOOL_FDBAUTH                40230
#define IDS_TOOL_FDBPASS                40231
#define IDS_TOOL_FDBPROXYADD            40232
#define IDS_TOOL_FDBPROXYPORT           40233
#define IDS_TOOL_FDBSERVER              40234
#define IDS_TOOL_FDBUSEPROXY            40235
#define IDS_TOOL_FDBUSER                40236
#define IDS_TOOL_FDBMAIL                40237
#define IDS_TOOL_FDBTIMEOUT             40238
#define IDS_READCDCONTENT               40239
#define IDS_UPDATETRACKLIST             40240
#define IDS_LANGUAGE                    40241
#define IDS_TL_TRACK                    40242
#define IDS_TL_TITLE                    40243
#define IDS_TL_TIME                     40244
#define IDS_TL_ESTSIZE                  40245
#define IDS_NOTRACKSSELECTED            40246
#define ID_CDDB_READFROMREMOTECDDBSERVER 40247
#define IDS_ENC_ID3FAILED               40248
#define ID_PREFERENCES_CDREADERSETTINGS 40249
#define IDS_ENC_ID3INTERR               40250
#define ID_EJECT_CD                     40251
#define ID_INVERT_SEL                   40254
#define ID_SWAP_TITLEARTIST             40255
#define ID_SWAP_ARTISTALBUM             40256
#define ID_ID3_CLEARALLFIELDS           40257
#define ID_ID3_CLEANUPTAGS              40258
#define ID_ID3_COPYID3V1ID3V2           40260
#define ID_ID3_COPYID3V2ID3V1           40261
#define ID_ID3_FIXVARIOUSARTISTAG       40262
#define ID_ALBUMTAGS_QUERYMUSICBRAINZDATABASE 40263
#define ID_ALBUMTAGS_SUBMITCDTOMUSICBRAINZDATABASE 40264
#define ID_AUTO_RIP                     40265
#define ID_CD_ABLUM_RIP                 40266
#define ID_RIP_CD                       40267
#define ID_ID3_FIX_NAME                 40268
#define IDS_BUGREPORTFORUM              61204
#define IDS_SUPPORTEDFILES              61205
#define IDS_ALLFILES                    61206
#define IDS_ATAPI                       61207
#define IDS_NONE                        61208
#define IDS_BIGENDIAN                   61209
#define IDS_LITTLEENDIAN                61210
#define IDS_READ                        61211
#define IDS_ENABLE                      61212
#define IDS_DENSITY                     61213
#define IDS_ENDIAN                      61214
#define IDS_RESULT                      61215
#define IDS_PASS                        61216
#define IDS_FAIL                        61217
#define IDS_STANDARD                    61218
#define IDS_PLEASE_SELECTLISTEDITEM     61219
#define IDS_AUTODEFECTWARNING           61220
#define IDS_PICTURE_SZFILTER            61221
#define IDS_TL_INSIZE                   61222
#define IDS_SELECTPRESETPATH            61223
#define IDS_SELECTTEMPPATH              61224
#define IDS_SELECTPRESETPATHTITLE       61225
#define IDS_SELECTTEMPPATHTITLE         61226
#define IDS_TOOL_USE2PHASE              61227
#define IDS_ENC_PHASE1_SUCCESS          61228
#define IDS_WORKING_ON_FILE             61229
#define IDS_NOTENOUGHDISKSPACE          61230
#define IDS_OPENTEMPFILE                61231
#define IDS_STARTINGPHASE2              61232
#define IDS_ENCODINGTEMPFILE            61233
#define IDS_PHASE2FINISHED              61234
#define IDS_WORKING_ON_ALBUM            61235
#define IDS_MB_QUERYFAILED              61236
#define IDS_MB_ERRORCONNECTING          61237
#define IDS_MB_NOENTRY                  61238
#define IDS_NBATCH_BEEP                 61239
#define IDS_NBATCH_RIP                  61240
#define IDS_NBATCH_EJECT                61241
#define IDS_NBATCH_FREEDB               61242
#define IDS_NBATCH_MUSICBRAINZ          61243
#define IDS_NBATCH_IFERROR              61244
#define IDS_NBATCH_CDPLAYERINI          61245
#define IDS_NBATCH_CDTEXT               61246
#define IDS_NBATCH_FINISH               61247
#define IDS_LANGCHANGED                 61248

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         40269
#define _APS_NEXT_CONTROL_VALUE         1382
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
