//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by lameFE.rc
//
#define RT_MANIFEST1                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LAMEFE_DIALOG               102
#define IDD_ENCODER_PAGE                107
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define IDR_ACCELERATOR1                130
#define IDR_ACCELERATOR                 130
#define IDD_PRESET                      134
#define IDD_SETTINGS                    139
#define IDD_ID3EDIT                     140
#define IDD_STATUS_DIALOG               142
#define IDI_NEXT                        150
#define IDI_STOP                        151
#define IDI_PREV                        152
#define IDI_PLAY                        153
#define IDI_PAUSE                       154
#define IDI_CD_WAV                      155
#define IDI_CD_MP3                      156
#define IDI_WAV_MP3                     157
#define IDI_EJECT                       159
#define IDD_LAMEFE_PAGE                 165
#define IDD_CDRIP_PAGE                  166
#define IDD_CDDB_SETUP                  168
#define IDR_SYSTRAY_MENU                171
#define IDD_CDDB_QUERY                  172
#define IDI_REFRESH                     174
#define IDI_START                       175
#define IDI_ENCODER                     176
#define IDI_CDDB                        177
#define IDI_ID3                         178
#define IDD_PLUGINPAGE                  185
#define SPLASH                          190
#define IDC_PRESET                      1001
#define IDC_LIST                        1005
#define IDC_ENCODE                      1006
#define IDC_ENCODING                    1015
#define IDC_SAMPLES                     1016
#define IDC_BITRATE                     1017
#define IDC_ORIG                        1020
#define IDC_COPY                        1021
#define IDC_SAVE                        1022
#define IDC_DELETE                      1025
#define IDC_PROGRESS_FILE               1026
#define IDC_PROGRESS_LIST               1027
#define IDC_STATUS                      1029
#define IDC_BEEP                        1042
#define IDC_PLAY                        1043
#define IDC_M3U                         1044
#define IDC_DLG                         1045
#define IDC_PATHCHK                     1046
#define IDC_PLAYER                      1049
#define IDC_STRPLAYER                   1050
#define IDC_PLAYER2                     1050
#define IDC_LAMEVERSION                 1051
#define IDC_FILES                       1053
#define IDC_SONG                        1055
#define IDC_ARTIST                      1056
#define IDC_ALBUM                       1057
#define IDC_COMMENT                     1058
#define IDC_YEAR                        1060
#define IDC_TRACK                       1061
#define IDC_FILEN                       1062
#define IDC_RENAME                      1064
#define IDC_GENRE                       1067
#define IDC_SAVE_PATH                   1068
#define IDC_LIST_STATUS_BAR             1071
#define IDC_LIST_STATUS_BAR2            1072
#define IDC_EST_SIZE                    1073
#define IDC_IN_SIZE                     1074
#define IDC_FILE_STATUS_BAR             1075
#define IDC_FILE_X_OF_Y                 1076
#define IDC_ERRORS                      1077
#define IDC_LIST_MSG                    1079
#define IDC_FILE_MSG                    1080
#define IDC_IN                          1081
#define IDC_OUT                         1082
#define IDC_ID3_TAG                     1083
#define IDC_PRESETS                     1084
#define IDC_SONG_A                      1089
#define IDC_ARTIST_A                    1090
#define IDC_ALBUM_A                     1091
#define IDC_COMMENT_A                   1092
#define IDC_GENRE_A                     1093
#define IDC_YEAR_A                      1094
#define IDC_TRACK_A                     1096
#define IDC_AM_ARTIST                   1097
#define IDC_AM_ALBUM                    1098
#define IDC_AM_GENRE                    1099
#define IDC_AM_COMMENT                  1100
#define IDC_AM_YEAR                     1101
#define IDC_FILE_NAME                   1103
#define IDC_PAUSE                       1105
#define IDC_STOP                        1106
#define IDC_PREV                        1107
#define IDC_NEXT                        1108
#define IDC_ID3TAG                      1109
#define IDC_ALBUM_MODE                  1110
#define IDC_CD_WAV                      1114
#define IDC_CD_MP3                      1115
#define IDC_WAV_MP3                     1116
#define IDC_REFRESH                     1117
#define IDC_EJECT_CD                    1128
#define IDC_ENCODER_VERSION             1130
#define IDC_BITSPERSAMPLE               1132
#define IDC_CHANNELS                    1133
#define IDC_COPYRIGHT                   1135
#define IDC_ORIGINAL                    1136
#define IDC_CHECKSUM                    1137
#define IDC_PRIVATE                     1138
#define IDC_ID3_2                       1139
#define IDC_OUTPUT                      1142
#define IDC_PLAYER_PATH                 1144
#define IDC_OUTPUT_PATH                 1145
#define IDC_FINISH_DLG                  1146
#define IDC_PLAY_FILES                  1148
#define IDC_SHUTDOWN                    1151
#define IDC_EXIT_FINISHED               1153
#define IDC_CD_DRIVE                    1154
#define IDC_CDROM_TYPE                  1155
#define IDC_RIPPING_METHOD              1156
#define IDC_EJECT                       1157
#define IDC_LOCK                        1158
#define IDC_SWAP                        1159
#define IDC_REMOTE_SERVER               1161
#define IDC_LOCATION                    1162
#define IDC_ADDRESS                     1163
#define IDC_PATH                        1164
#define IDC_PROTOCOLL                   1165
#define IDC_REMOTE_PORT                 1166
#define IDC_EMAIL                       1167
#define IDC_TIMEOUT                     1168
#define IDC_PROXY                       1169
#define IDC_USE_PROXY                   1170
#define IDC_PROXY_PORT                  1171
#define IDC_USERNAME                    1172
#define IDC_PASSWORD                    1173
#define IDC_Version                     1174
#define IDC_CD_SPEED                    1175
#define IDC_CD_SPIN_UP                  1176
#define IDC_NATIVE                      1177
#define IDC_START                       1181
#define IDC_AUTHENTICATION              1183
#define IDC_UPDATE                      1184
#define IDC_CDDB                        1185
#define IDC_SELECT_ALL                  1189
#define IDC_EST_TIME                    1190
#define IDC_ELA_TIME                    1191
#define IDC_REM_TIME                    1192
#define IDC_MPEG                        1193
#define IDC_FORMAT                      1194
#define IDC_SUBDIR                      1195
#define IDC_SILENT                      1196
#define IDC_LIST_TITLE                  1197
#define IDC_PLUGINS                     1198
#define IDC_PLUGINPATH                  1200
#define IDC_INSTALLED_PLUGINS           1202
#define IDC_CONFIGURE                   1203
#define IDC_INSTALL                     1204
#define IDC_UNINSTALL                   1205
#define IDC_DISPLAY_STATIC              1206
#define IDC_JITTERSTATUS                1209
#define ID_ADD_FILE                     40001
#define ID_REMOVE_FILE                  40002
#define ID_EXIT                         40003
#define ID_TAGEDIT                      40004
#define ID_SETTINGS                     40005
#define ID_ABOUT                        40006
#define ID_PRESET                       40007
#define IDS_MAIN_ADDFILECD              40007
#define IDS_NOFILESSELECTED             40008
#define IDS_EMPTYLIST                   40009
#define IDS_MAIN_NOAUDIOCD              40010
#define ID_TOOLS_EDITID3TAG             40011
#define IDS_NOTRACKSSELECTED            40011
#define IDS_DATATRACK                   40012
#define IDS_DRIVENOTREADY               40013
#define ICD_CDDB_SETTINGS               40014
#define IDS_ERRTOC                      40014
#define ID_CDDB_READFROMREMOTECDDBSERVER 40015
#define IDS_MAIN_LIST_TITLE             40015
#define ID_PREFERENCES_TAGWRITERSETTINGS 40016
#define IDS_ENC_ID3FAILED               40016
#define ID_PREFERENCES_CDREADERSETTINGS 40017
#define IDS_ENC_WRITEID3                40017
#define IDC_ST_RESTORE                  40018
#define IDS_ENC_ID3INTERR               40018
#define IDC_ST_EXIT                     40019
#define IDS_ENC_LOGENTRY                40019
#define ID_EDIT_ID3                     40020
#define IDS_ENC_LOGFAILED               40020
#define ID_ADD                          40021
#define IDS_ENC_FILEEXISTS              40021
#define ID_REMOVE                       40022
#define IDS_ENC_DENIEDOVWR              40022
#define IDS_ENC_ERRDIRCREATE            40023
#define IDS_ENC_TOOLTIP                 40024
#define IDS_ENC_INITERR                 40025
#define IDS_ENC_SUCCESS                 40026
#define IDS_ENC_PREPARING               40027
#define IDS_ENC_RIPPING                 40028
#define ID_PREFERENCES_PLUGINS          40028
#define IDS_ENC_RIPPERROR               40029
#define ID_HELP_HELPINDEX               40029
#define IDS_ENC_NUMERRORS               40030
#define ID_HELP_LICENSE                 40030
#define IDS_ENC_VIEW_LOG_ERR            40031
#define IDS_ENC_VIEW_LOG                40032
#define IDS_ENC_FILE_XOFY               40033
#define IDS_ENC_TRACK_XOFY              40034
#define IDS_ENC_EXTRACT_TRACK           40035
#define IDS_ENC_JITTER_ERR              40036
#define IDS_ENC_FINISHED                40037
#define IDS_ENC_CLOSE_BTN               40038
#define IDS_ENC_WRITE_M3U               40039
#define IDS_ENC_SAVED_M3U               40040
#define IDS_ENC_FAILED_M3U              40041
#define IDS_ENC_WAVE_ENC                40042
#define IDS_ENC_WAVE_FILES              40043
#define IDS_CDDB_ERR_CFGWRITE           40044
#define IDS_CDDB_ERR_CFGREAD            40045
#define IDS_CDDB_ERR_WINSOCK            40046
#define IDS_CDDB_ERR                    40047
#define IDS_MAIN_LIST_TITLE2            40048
#define IDS_CDDBONWAVERR                40049
#define IDS_MAIN_DATATRACK              40050
#define IDS_ID3_ALBUMMODE               40051
#define IDS_NOSELECTION                 40052
#define IDS_ID3_ARTISTMODE              40053
#define IDS_ID3_COMMENTMODE             40054
#define IDS_ID3_GENREMODE               40055
#define IDS_ID3_YEARMODE                40056
#define IDS_FILEOPENERR                 40057
#define IDS_INVBITRATE                  40058
#define IDS_RESTARTLAME                 40059

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         40033
#define _APS_NEXT_CONTROL_VALUE         1210
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
